spring.application.name=SCM
# Database URL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/scm_db
spring.datasource.username=root
spring.datasource.password=Akhilsharma25b@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


