spring.application.name=SCM
# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/scm_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver class
#spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect